repos:
  - repo: local
    hooks:
      - id: build
        name: Build code
        entry: python -m tox -e build
        language: system
        pass_filenames: false
      - id: format
        name: Format code
        entry: python -m tox -e format
        language: system
        pass_filenames: false
      - id: lint
        name: Lint code
        entry: python -m tox -e lint
        language: system
        pass_filenames: false
      - id: test
        name: Test code
        entry: python -m tox -e test
        language: system
        pass_filenames: false
