# Name the workflow
name: Publish to PyPI

# Trigger the workflow when a new release is published
on:
  release:
    types: [published]

# Define the jobs that will be run
jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python and specify the Python version to use
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Install the dependencies needed to build and publish the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[devs]

      # Build the package
      - name: Build package
        run: |
          inv build

      # Publish the package to PyPI using the twine
      - name: Publish package
        run: |
          inv release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
