# Name the workflow
name: Test

# Trigger the workflow when there is a push or pull request event on the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Define the jobs that will be run
jobs:
  test:
    name: Test Package
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python and specify the Python version to use
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Install the dependencies needed to build and test the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[devs]

      # Run tests with pytest and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          tox -e test

      # Upload the coverage report to Coveralls
      - name: Upload coverage report to Coveralls
        run: coveralls
        env:
          # Set the Coveralls repo token
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
